#!/usr/bin/env python3
"""
calibrate_rans.py -- algo/agrijpeg-core (v2, RLE alphabet)
=============================================================
v2: calibrates on standard JPEG (run,size)/category symbols (zigzag
order, EOB/ZRL) instead of raw coefficient values -- this is what lets
rANS actually beat Huffman (v1 rANS-coded all 63 raw AC values per
block including every trailing zero individually, losing to Huffman's
near-free EOB). Same dataset, same jpeg-baseline settings, same
dump_coeffs pattern otherwise.

Alphabet: DC = size category (0-15, 16 symbols). AC = (run<<4)|size byte
(0-255, 256 symbols, includes EOB=0x00 and ZRL=0xF0). No escape
mechanism needed -- both alphabets are naturally bounded (a byte).

Usage (from calibration-agrijpeg/, after `make dump_coeffs`):
    python3 calibrate_rans.py
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

import cv2
import numpy as np

BASELINE_QUALITY = "75"
BASELINE_SAMPLE = "2x2,1x1,1x1"

PROB_BITS = 14
PROB_SCALE = 1 << PROB_BITS

DC_N_SYMBOLS = 16   # size categories 0-15
AC_N_SYMBOLS = 256  # (run<<4)|size byte, incl. EOB=0x00, ZRL=0xF0


def find_dataset_inputs(dataset_dir: str):
    all_files = sorted(os.listdir(dataset_dir))
    seen_ids = set()
    inputs = []
    for f in all_files:
        if not f.lower().endswith((".ppm", ".png")):
            continue
        image_id = os.path.splitext(f)[0]
        if image_id in seen_ids:
            continue
        ppm_path = os.path.join(dataset_dir, image_id + ".ppm")
        png_path = os.path.join(dataset_dir, image_id + ".png")
        chosen = ppm_path if os.path.exists(ppm_path) else png_path
        inputs.append(chosen)
        seen_ids.add(image_id)
    return inputs


def run_pipeline(inputs, cjpeg_bin: str, dump_coeffs_bin: str, prefix: str, tmp_dir: str):
    jpg_path = os.path.join(tmp_dir, "cal.jpg")
    ppm_path = os.path.join(tmp_dir, "cal_input.ppm")

    for i, src_path in enumerate(inputs):
        if src_path.lower().endswith(".png"):
            img = cv2.imread(src_path)
            if img is None:
                print(f"  WARNING: could not read {src_path}, skipping", file=sys.stderr)
                continue
            cv2.imwrite(ppm_path, img)
            cjpeg_input = ppm_path
        else:
            cjpeg_input = src_path

        cmd = [cjpeg_bin, "-quality", BASELINE_QUALITY,
               "-sample", BASELINE_SAMPLE, "-outfile", jpg_path, cjpeg_input]
        result = subprocess.run(cmd, capture_output=True)
        if result.returncode != 0:
            print(f"  WARNING: cjpeg failed on {src_path}, skipping "
                  f"({result.stderr.decode(errors='replace')})", file=sys.stderr)
            continue

        result = subprocess.run([dump_coeffs_bin, jpg_path, prefix], capture_output=True)
        if result.returncode != 0:
            print(f"  WARNING: dump_coeffs failed on {jpg_path}, skipping "
                  f"({result.stderr.decode(errors='replace')})", file=sys.stderr)
            continue

        if (i + 1) % 100 == 0 or i == len(inputs) - 1:
            print(f"  {i + 1}/{len(inputs)} images processed")


def build_table(sym_path: str, n_symbols: int, chunk_bytes: int = 50_000_000):
    """Streams a flat byte-symbol file, with +1 Laplace smoothing (see v1's
    own note: never let an in-alphabet symbol reach exactly zero probability)."""
    if not os.path.exists(sym_path) or os.path.getsize(sym_path) == 0:
        raise RuntimeError(f"No calibration data at {sym_path} -- did the pipeline run?")

    freqs = np.ones(n_symbols, dtype=np.int64)
    n_total = 0
    with open(sym_path, "rb") as f:
        while True:
            chunk = np.fromfile(f, dtype=np.uint8, count=chunk_bytes)
            if chunk.size == 0:
                break
            n_total += chunk.size
            counts = np.bincount(chunk, minlength=n_symbols)
            freqs += counts[:n_symbols]
    return freqs, n_total


def normalize_freqs(freqs: np.ndarray, target_total: int) -> np.ndarray:
    total = freqs.sum()
    scaled = np.floor(freqs.astype(np.float64) * target_total / total).astype(np.int64)
    scaled[(freqs > 0) & (scaled == 0)] = 1
    diff = target_total - scaled.sum()
    if diff != 0:
        idx = int(np.argmax(scaled))
        scaled[idx] += diff
    if (scaled <= 0).any():
        raise RuntimeError("Normalization produced a non-positive frequency.")
    return scaled


def emit_header(tables: dict, out_path: str):
    lines = [
        "/*",
        " * rans_tables.h -- AUTO-GENERATED by calibrate_rans.py (v2, RLE alphabet)",
        " * Calibrated against algo/jpeg-baseline's own JPEG output",
        f" * (quality={BASELINE_QUALITY}, sample={BASELINE_SAMPLE}).",
        " * DC = size category (0-15). AC = (run<<4)|size byte (0-255).",
        " * Do not hand-edit -- rerun the calibration script instead.",
        " */",
        "#ifndef RANS_TABLES_H",
        "#define RANS_TABLES_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define RANS_PROB_BITS {PROB_BITS}",
        f"#define RANS_DC_N_SYMBOLS {DC_N_SYMBOLS}",
        f"#define RANS_AC_N_SYMBOLS {AC_N_SYMBOLS}",
        "",
    ]
    for name, freqs in tables.items():
        n = len(freqs)
        values_str = ", ".join(str(int(v)) for v in freqs)
        lines.append(f"static const uint32_t RANS_FREQ_{name.upper()}[{n}] = {{")
        lines.append(f"    {values_str}")
        lines.append("};")
        lines.append("")
    lines.append("#endif /* RANS_TABLES_H */")

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out_path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dataset", default="images")
    parser.add_argument("--cjpeg", default=None)
    parser.add_argument("--dump-coeffs", default="./dump_coeffs")
    parser.add_argument("--out", default="rans_tables.h")
    args = parser.parse_args()

    cjpeg_bin = args.cjpeg or shutil.which("cjpeg")
    if not cjpeg_bin:
        print("No cjpeg found: pass --cjpeg /path/to/cjpeg, or install one on PATH.", file=sys.stderr)
        sys.exit(1)
    if not os.path.exists(args.dump_coeffs):
        print(f"{args.dump_coeffs} not found -- build it first: make dump_coeffs", file=sys.stderr)
        sys.exit(1)

    inputs = find_dataset_inputs(args.dataset)
    if not inputs:
        print(f"No .ppm/.png images found in {args.dataset}", file=sys.stderr)
        sys.exit(1)
    print(f"Calibrating on {len(inputs)} images from {args.dataset}...")

    with tempfile.TemporaryDirectory() as tmp:
        prefix = os.path.join(tmp, "cal")
        run_pipeline(inputs, cjpeg_bin, args.dump_coeffs, prefix, tmp)

        tables = {}
        for suffix, name, n_sym in [("_y_dc.sym", "y_dc", DC_N_SYMBOLS),
                                      ("_y_ac.sym", "y_ac", AC_N_SYMBOLS),
                                      ("_c_dc.sym", "c_dc", DC_N_SYMBOLS),
                                      ("_c_ac.sym", "c_ac", AC_N_SYMBOLS)]:
            path = prefix + suffix
            raw_freqs, n_total = build_table(path, n_sym)
            print(f"{name}: {n_total} symbols")
            tables[name] = normalize_freqs(raw_freqs, PROB_SCALE)

        emit_header(tables, args.out)


if __name__ == "__main__":
    main()
